# Generated by Django 4.2.4 on 2023-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_letter',
            field=models.FileField(default=1, upload_to='admission_letter/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
