# Generated by Django 4.2.4 on 2024-06-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('lms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_student', to='Account.studentuserprofile'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentuserprofile'),
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='Account.studentuserprofile'),
        ),
        migrations.AlterField(
            model_name='studentfavouritecourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentuserprofile'),
        ),
    ]
