# Generated by Django 4.2.4 on 2023-11-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_api.student')),
            ],
        ),
    ]
