# Generated by Django 4.2.4 on 2023-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0002_studentassignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='student/assignments/submission'),
        ),
    ]
