# Generated by Django 4.2.4 on 2023-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0002_student_admission_letter_student_password2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interested_categories',
            new_name='interested_course',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
