# Generated by Django 4.2.4 on 2023-08-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0003_rename_interested_categories_student_interested_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
