# Generated by Django 4.2.13 on 2024-07-05 16:20

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('postal', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('is_teacher', models.BooleanField(default=True)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('code_expiration', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('reg_no', Account.models.CustommRegField(max_length=26, unique=True)),
                ('postal', models.CharField(blank=True, max_length=30, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('code_expiration', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
