# Generated by Django 4.2.4 on 2023-12-02 00:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('postal', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('is_teacher', models.BooleanField(default=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('reg_no', models.CharField(max_length=26, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid registration number in the specified format', regex='^[a-zA-Z]+/[a-zA-Z]+/[a-zA-Z]+\\.[a-zA-Z]+/[a-zA-Z]+/\\d{4}/\\d{3}$')])),
                ('postal', models.CharField(max_length=30)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
