# Generated by Django 4.2.4 on 2023-12-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheruserprofile',
            old_name='skills',
            new_name='course',
        ),
    ]
