# Generated by Django 4.2.4 on 2023-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuserprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacheruserprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
