# Generated by Django 4.2.4 on 2023-12-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_studentuserprofile_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuserprofile',
            name='code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacheruserprofile',
            name='code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
